-- =============================================================================
-- QX Nexus — Seed Data & Auth Trigger Migration
--
-- IMPORTANT: Seeding auth.users via plain SQL is NOT reliable in hosted
-- Supabase. The GoTrue auth service manages auth.users with internal
-- triggers, password hashing (bcrypt/argon2), email confirmation state,
-- and JWT secret binding. Direct INSERT into auth.users will:
--   - Skip password hashing (login will fail)
--   - Bypass email confirmation flow
--   - Miss internal GoTrue bookkeeping (sessions, refresh tokens)
--
-- RECOMMENDED APPROACH: Use the Supabase Admin API to create auth users,
-- then let the auto-profile trigger (defined below) create the profiles.
--
-- This migration provides:
--   1. A trigger on auth.users → auto-create profile on signup
--   2. A JavaScript seed script (supabase/seed.ts) using the Admin API
--   3. Fallback SQL profiles (requires auth users created first via API/Dashboard)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Auto-create profile on new auth user signup
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, role, must_change_password)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'role', 'member'),
    COALESCE((NEW.raw_user_meta_data->>'must_change_password')::boolean, false)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 2. Seed profiles (run AFTER auth users are created via Admin API)
--
-- The user IDs below MUST match the UUIDs generated by auth.admin.createUser().
-- Replace the placeholder UUIDs with actual IDs after running the seed script.
--
-- Example workflow:
--   1. Run supabase/seed.ts (creates auth users, returns UUIDs)
--   2. Update the UUIDs below
--   3. Run this migration (or execute the UPDATE statements)
-- ---------------------------------------------------------------------------

-- Placeholder profiles — update IDs after auth user creation
-- These will fail if auth.users rows don't exist yet.
-- Uncomment and run AFTER creating auth users via Admin API.

/*
UPDATE public.profiles SET
  employee_id = 'EMP001',
  username = 'Super Admin',
  role = 'superadmin',
  must_change_password = true,
  job_title = 'System Administrator',
  base_office = 'Bengaluru'
WHERE id = '<super-admin-uuid>';

UPDATE public.profiles SET
  employee_id = 'EMP002',
  username = 'Admin',
  role = 'admin',
  must_change_password = true,
  project_id = (SELECT id FROM public.projects WHERE project_code = 'QXN' LIMIT 1),
  job_title = 'Project Administrator',
  base_office = 'Bengaluru'
WHERE id = '<admin-uuid>';

UPDATE public.profiles SET
  employee_id = 'EMP003',
  username = 'Lead',
  role = 'lead',
  must_change_password = true,
  project_id = (SELECT id FROM public.projects WHERE project_code = 'QXN' LIMIT 1),
  squad_id = (SELECT id FROM public.squads WHERE squad_code = 'QA-1' LIMIT 1),
  reports_to = '<admin-uuid>',
  job_title = 'QA Lead',
  base_office = 'Bengaluru'
WHERE id = '<lead-uuid>';

UPDATE public.profiles SET
  employee_id = 'EMP004',
  username = 'Member',
  role = 'member',
  must_change_password = true,
  project_id = (SELECT id FROM public.projects WHERE project_code = 'QXN' LIMIT 1),
  squad_id = (SELECT id FROM public.squads WHERE squad_code = 'QA-1' LIMIT 1),
  reports_to = '<lead-uuid>',
  job_title = 'QA Engineer',
  base_office = 'Mumbai'
WHERE id = '<member-uuid>';
*/

-- ---------------------------------------------------------------------------
-- 3. Seed reference data (safe to run — no auth.users dependency)
-- ---------------------------------------------------------------------------

-- Default project
INSERT INTO public.projects (project_code, project_name, description, active)
VALUES ('QXN', 'QX Nexus', 'Main QA Operations project', true)
ON CONFLICT (project_code) DO NOTHING;

-- Default squad
INSERT INTO public.squads (project_id, squad_code, squad_name, description, active)
SELECT
  p.id,
  'QA-1',
  'QA Squad Alpha',
  'Primary QA execution squad',
  true
FROM public.projects p
WHERE p.project_code = 'QXN'
ON CONFLICT (project_id, squad_code) DO NOTHING;

-- Default release
INSERT INTO public.releases (name)
VALUES ('Release 1.0')
ON CONFLICT DO NOTHING;

-- Default sprint
INSERT INTO public.sprints (name, start_date, end_date)
VALUES ('Sprint 1', CURRENT_DATE, CURRENT_DATE + INTERVAL '14 days')
ON CONFLICT DO NOTHING;

-- Default holidays (example)
INSERT INTO public.holidays (date, name, type, year, created_by)
VALUES
  ('2026-01-26', 'Republic Day', 'Holiday', 2026, 'system'),
  ('2026-03-30', 'Ugadi', 'Holiday', 2026, 'system'),
  ('2026-04-14', 'Dr. Ambedkar Jayanti', 'Holiday', 2026, 'system'),
  ('2026-05-01', 'May Day', 'Holiday', 2026, 'system'),
  ('2026-08-15', 'Independence Day', 'Holiday', 2026, 'system'),
  ('2026-10-02', 'Gandhi Jayanti', 'Holiday', 2026, 'system'),
  ('2026-10-20', 'Diwali', 'Holiday', 2026, 'system'),
  ('2026-11-05', 'Diwali (Govardhan Puja)', 'Optional Holiday', 2026, 'system'),
  ('2026-12-25', 'Christmas', 'Holiday', 2026, 'system')
ON CONFLICT DO NOTHING;

-- Default custom fields
INSERT INTO public.custom_fields (label, type, applies_to)
VALUES
  ('Environment', 'select', 'dataEntry'),
  ('Browser', 'select', 'defect'),
  ('Device', 'select', 'both')
ON CONFLICT DO NOTHING;

-- Update custom field options via jsonb
UPDATE public.custom_fields SET options = ARRAY['Dev','QA','Staging','Production']
WHERE label = 'Environment' AND applies_to = 'dataEntry';

UPDATE public.custom_fields SET options = ARRAY['Chrome','Firefox','Safari','Edge']
WHERE label = 'Browser' AND applies_to = 'defect';

UPDATE public.custom_fields SET options = ARRAY['Desktop','Mobile','Tablet']
WHERE label = 'Device' AND applies_to = 'both';
